bbb/bbb/urls.py
from django.contrib import admin
from django.urls import include, path

#import views from root directory of project


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bricks.urls')),
]

bbb/bricks/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static
#import views from root directory of project
from . import views
from django.conf import settings
app_name = 'bricks'
urlpatterns = [
    path('', views.index,name='index' ),
    path('about/', views.about, name='about'),
    path('login/', views.login, name='login'),
    path('property/<property_id>/', views.property, name='property'),
    path('home/', views.home, name='home'),
    path('payment/', views.payment, name='payment'),
    path('purchase/', views.purchase, name='purchase'),
    path('sell/', views.sell, name='sell'),
    path('buy/',views.buy,name='buy'),
    path('gift2/',views.gift2,name='gift2'),
    path('success/',views.success, name="success"),
    path('convert/', views.convert, name='convert'),
    path('actions/', views.actions, name='actions'),
    path('faq/', views.faq, name='faq'),
    path('prospectus/', views.prospectus, name='prospectus'),
    path('registration/',views.registration, name='registration'),
    path('legal/', views.legal, name='about'),
    path('savings/', views.regular_saving_scheme, name='regular_saving_scheme'),
    path('notices/', views.notices, name='notices'),
    path('gift/', views.gift, name='gift'),
    path('settings/', views.settings, name='settings'),
    path('structure/', views.structure, name='structure'),
    path('privacy/', views.privacy_policy, name='privacy_policy'),
    path('tandc/', views.terms_and_conditions, name='terms_and_conditions'),
    path('properties/', views.IndexView.as_view(), name='properties'),
    path('payment/', views.payment, name='payment'),
	path('recieving/', views.receiving_bank, name='receiving_bank'),
	path('team/',views.team, name='team'),
	path('logintoo/',views.logintoo, name='logintoo'),
    path('charts/',views.charts,name='charts'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('registertoo/', views.registertoo, name='registertoo'),
    path('registerthree/', views.registerthree, name='registerthree'),
    path('kyc/', views.kyc, name='kyc'),
    path('convert/',views.convert, name='convert')


    ]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bbb/bricks/models.py
import datetime
# Create your models here.

#import models from django.db

#unlike RoR migrations are made directly from the models

from django.db import models
from django.utils import timezone

#Property Model
class Property(models.Model):
	road = models.CharField(max_length = 250)
	town = models.CharField(max_length = 250)
	postcode = models.CharField(max_length = 10)
	description = models.CharField(max_length = 10000)
	features = models.CharField(max_length = 2000)
	pub_date = models.DateTimeField('date published')
	image = models.ImageField(default="images/logo.png",upload_to = 'images/properties')
	title = models.CharField(max_length = 250,default = "Property Title")
	expiry_date = models.DateTimeField


	def __str__(self):
		return self.title


	def was_published_less_than_a_day(self):
		return self.pub_date >= timzezone.now() - datetime.timedelta(days=1)

	def was_published_less_than_a_week(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=7)


	def expiring_in_less_than_a_week(self):
		return self.expiry_date - timezone.now() <= datetime.timedelta(days=7)


	def expiring_in_less_than_a_month(self):
		return self.expiry_date - timezone.now() <= datetime.timedelta(days=31)


	def expiring_in_less_than_a_year(self):
		return self.expiry_date - timezone.now() <= datetime.timedelta(days=365)


# Stipe or Payment provider




# User model


class User(models.Model):
	first_name = models.CharField(max_length = 50)
	last_name = models.CharField(max_length = 50)
	email= models.CharField(max_length = 100)
	phone_number= models.CharField(max_length=15)
	postcode = models.CharField(max_length = 10)
	address = models.CharField(max_length = 400)
	password = models.CharField(max_length = 250)


	def __str__(self):
		return self.first_name + self.last_name





# Favorites  add a many to many through favourites relationship

bbb/bricks/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.urls import reverse
from django.views import generic

import sys

from .models import Property,User



class IndexView(generic.ListView):
	"""docstring for IndexView."""

	template_name = "properties.html"
	property_list = Property.objects.order_by('-pub_date')
	model =  Property



# Create your views here.

def actions(request):
	return  render(request, 'actions.html')

def index(request):

	property_list = Property.objects.order_by('-pub_date')[:5]
	output = ', '.join([l.title for l in property_list])
	return render(request, 'index.html')


def registertoo(request):
	return render(request, 'registertoo.html')

def registerthree(request):
	return render(request, 'registerthree.html')

def kyc(request):
	return render(request, 'kyc.html')
def properties(request):
	property_list = Property.objects.order_by('-pub_date')[:5]
	output = ', '.join([l.title for l in property_list])

	context = {
		'property_list': property_list
	}
	return render(request, 'properties.html',context)



def login(request):
	return render(request, "login.html")

	# return HttpResponse("You're in the login page")


def home(request):
	return render(request, "home")

	# return HttpResponse("DASHBOARD Number of Bs, Current price, Current Value Held, Average Price Held rows of prices and then 3 cards with pie charts with national average and london average and the target")


def purchase(request):
	return HttpResponse("Amount and Units is it a gift, name of the recipient,email of the recipient, account number, would you like to lock the gift until the recipient reaches a certain age")


def logintoo(request):
	return render(request, "logintoo.html")


def sell(request):
	return render(request,"sell.html")

def buy(request):
	return render(request,"buy.html")
def gift2(request):
	return render(request,"gift2.html")

def success(request):
	return render(request,'success.html')

def convert(request):

	return HttpResponse( "\(warning of  at least 4 weeks notice) Date of Conversion, Amount to convert, Address to be acquired postcode lookup (GOOGLE PLACS) Solicitor Name, Email and Telephone, Total acquisition Price, Mortgage Details ")

def charts(request):
	return render(request, "charts.html")

def dashboard(request):
	return render(request, "dashboard.html")

def payment(request):

	return render(request, "payment.html")

def convert(request):
	return render(request, "convert.html")
def receiving_bank(request):
	return HttpResponse("Account Name and Account Number Bank and Sort Code")


def registration(request):
	u = User()

	try:
		u.first_name = request.POST['first_name']
		u.last_name = request.POST['last_name']
		u.postcode = request.POST['postcode']
		u.email = request.POST['email']
		u.phone_number = request.POST['phone_number']

		u.save()
		print(f'{u}')
		return render(request,'registration.html',{'success': "Congratulations you signed up!",})


	except:
		print("something is wrong!!! ")
		return render(request,'registration.html',{'error_message' : "Something went wrong  try again! ",})


def property(request,property_id):
	try:
		property = Property.objects.get(pk=property_id)
	except Property.DoesNotExist:
		raise Http404(" Property does not exist!! :( ")



	#property = get_object_or_404(Property,property_id)
	print(property)
	return render(request,'property.html', {'property': property})

def team(request):
	return render(request, 'team.html')
def structure(request):
	return render(request, "structure.html")

	# return HttpResponse("Org  structure")


def prospectus(request):
	return render(request, "prospectus.html")

def faq(request):
	return render(request, "faq.html")

	# return HttpResponse("List of Faq rows with drop down answers")


def settings(request):
	return render(request, "settings.html")

	# return HttpResponse("Edit name surname, email address, password, target saving amount " )


def regular_saving_scheme(request):
	return render(request, "savings.html")

	# return HttpResponse("Account Name, Bank Account, Sort Code, Savings Amount Token Amount, Pause Saving Scheme, Stop Saving Scheme")

def terms_and_conditions(request):
	return render(request, "tandc.html")

	# return HttpResponse("TnC")

def privacy_policy(request):
	return render(request, "privacy.html")

	# return HttpResponse("Privacy policy set out here")


def legal(request):
	return render(request, "legal.html")

	# return HttpResponse(" Legal information ")

def about(request):
	return render(request, "about.html")

	# return HttpResponse(" About page")



def gift(request):
	return render(request, "gift.html")

	# return HttpResponse(" generates an email or notification in the app on the dashboard, youve been sent a gift of .. ")


def notices(request):
	return render(request, "notices.html")

	# return HttpResponse(" Put notices of changes or gifts received or sent opened and auctioned")

bbb/bricks/templates/about.html
{% extends "base.html" %}

{% block content %}
<h1> About</h1>
{% endblock %}

bbb/bricks/templates/base.1.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <style type="text/css">
    :root {
  --input-padding-x: 1.5rem;
  --input-padding-y: 0.75rem;
}

.login,
.image {
  min-height: 100vh;
}

.bg-image {
  background-image: url('https://source.unsplash.com/WEQbe2jBg40/600x1200');
  background-size: cover;
  background-position: center;
}

.login-heading {
  font-weight: 300;
}

.btn-login {
  font-size: 0.9rem;
  letter-spacing: 0.05rem;
  padding: 0.75rem 1rem;
  border-radius: 2rem;
}

.form-label-group {
  position: relative;
  margin-bottom: 1rem;
}

.form-label-group>input,
.form-label-group>label {
  padding: var(--input-padding-y) var(--input-padding-x);
  height: auto;
  border-radius: 2rem;
}

.form-label-group>label {
  position: absolute;
  top: 0;
  left: 0;
  display: block;
  width: 100%;
  margin-bottom: 0;
  /* Override default `<label>` margin */
  line-height: 1.5;
  color: #495057;
  cursor: text;
  /* Match the input under the label */
  border: 1px solid transparent;
  border-radius: .25rem;
  transition: all .1s ease-in-out;
}

.form-label-group input::-webkit-input-placeholder {
  color: transparent;
}

.form-label-group input:-ms-input-placeholder {
  color: transparent;
}

.form-label-group input::-ms-input-placeholder {
  color: transparent;
}

.form-label-group input::-moz-placeholder {
  color: transparent;
}

.form-label-group input::placeholder {
  color: transparent;
}

.form-label-group input:not(:placeholder-shown) {
  padding-top: calc(var(--input-padding-y) + var(--input-padding-y) * (2 / 3));
  padding-bottom: calc(var(--input-padding-y) / 3);
}

.form-label-group input:not(:placeholder-shown)~label {
  padding-top: calc(var(--input-padding-y) / 3);
  padding-bottom: calc(var(--input-padding-y) / 3);
  font-size: 12px;
  color: #777;
}
  </style>
    <title>Bricks</title>
  </head>
  <body>
  <!--  <header>-->
  <!--      <nav class="navbar navbar-expand-lg navbar-light bg-light">-->
  <!--<a class="navbar-brand" href="#">Bricks Alpha</a>-->
  <!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
  <!--  <span class="navbar-toggler-icon"></span>-->
  <!--</button>-->

  <!--<div class="collapse navbar-collapse" id="navbarSupportedContent">-->
  <!--  <ul class="navbar-nav mr-auto">-->
  <!--    <li class="nav-item active">-->
  <!--      <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>-->
  <!--    </li>-->
  <!--    <li class="nav-item active">-->
  <!--      <a href="/properties" class="nav-link">Properties</a>-->
  <!--    </li>-->

  <!--    <li class="nav-item dropdown">-->
  <!--      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
  <!--        *-->
  <!--      </a>-->
  <!--      <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
  <!--        <a class="dropdown-item" href="/prospectus">Prospectus</a>-->
  <!--        <a href="/structure" class="dropdown-item">Structure</a>-->
  <!--        <a class="dropdown-item" href="/tandc">Terms and Conditons</a>-->
  <!--        <a href="/settings" class="dropdown-item">Settings</a>-->
  <!--        <a href="/privacy" class="dropdown-item">Privacy</a>-->
  <!--        <a href="/team" class="dropdown-item">Team</a>-->
  <!--        <a href="/gift" class="dropdown-item">Gift</a>-->
  <!--        <div class="dropdown-divider"></div>-->
  <!--        <a class="dropdown-item" href="/legal">Legals</a>-->
  <!--      </div>-->
  <!--    </li>-->

  <!--    <li class="nav-item">-->
  <!--      <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Extra Pages</a>-->
  <!--    </li>-->
  <!--  </ul>-->
  <!--      <form class="form-inline my-2 my-lg-0">-->
  <!--        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
  <!--        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
  <!--      </form>-->
  <!--    </div>-->
  <!--  </nav>-->
  <!--  </header>-->
    
          {% block content %}
          {% endblock %}

    <footer>

    </footer>
  </body>
</html>

bbb/bricks/templates/index.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/videoheader.css' %}">

</head>

<header>
  <div class="overlay"></div>
  <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
    <source src="https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4" type="video/mp4">
  </video>
  <div class="container h-100">
    <div class="d-flex h-100 text-center align-items-center">
      <div class="w-100 text-white">
        <h1 class="display-3">Welcome to Brick by Bricks</h1>
        <p class="lead mb-0"> The new frontier of property investing</p>
      </div>
    </div>
  </div>
</header>

  <div class="container">

    <div class="row">
      <div class="col-md-8 mb-5">
        <h2>What We Do</h2>
        <hr>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A deserunt neque tempore recusandae animi soluta quasi? Asperiores rem dolore eaque vel, porro, soluta unde debitis aliquam laboriosam. Repellat explicabo, maiores!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis optio neque consectetur consequatur magni in nisi, natus beatae quidem quam odit commodi ducimus totam eum, alias, adipisci nesciunt voluptate. Voluptatum.</p>
        <a class="btn btn-primary btn-lg" href="#">Call to Action &raquo;</a>
      </div>
      <div class="col-md-4 mb-5">
        <h2>Contact Us</h2>
        <hr>
        <address>
          <strong>Shepherds Bush</strong>
          <br>3481 Melrose Place
          <br>London, United Kingdom
          <br>
        </address>
        <address>
          <abbr title="Phone">P:</abbr>
          +447415824776
          <br>
          <abbr title="Email">E:</abbr>
          <a href="mailto:#">eai267@g.harvard.edu</a>
        </address>
      </div>
    </div>
    <!-- /.row -->

    <div class="row">
      <div class="col-md-4 mb-5">
        <div class="card h-100">
          <img class="card-img-top" src="http://picsum.photos/300/200/?random" alt="">
          <div class="card-body">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Find Out More!</a>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-5">
        <div class="card h-100">
          <img class="card-img-top" src="http://picsum.photos/300/200/?random" alt="">
          <div class="card-body">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus totam ut praesentium aut.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Find Out More!</a>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-5">
        <div class="card h-100">
          <img class="card-img-top" src="http://picsum.photos/300/200/?random" alt="">
          <div class="card-body">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Find Out More!</a>
          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->

  </div>
{% endblock %}

bbb/bricks/templates/notices.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<header class="bg-primary py-5 mb-5" style="background: url("http://picsum.photos/1600/400"); background-size: cover;">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-lg-12">
          <img src="{% static "testheart.png" %}" alt="My image">

        <h1 class="display-4 text-white mt-5 mb-2">Notices</h1>
        <p class="lead mb-5 text-white-50">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non possimus ab labore provident mollitia. Id assumenda voluptate earum corporis facere quibusdam quisquam iste ipsa cumque unde nisi, totam quas ipsam.</p>
      </div>
    </div>
  </div>
</header>
{% endblock %}

bbb/bricks/templates/offline.html
charts.html

bbb/bricks/templates/properties.html
{% extends "base.html" %}
{% block content %}


<div class="container">
	<div class="row">
		{% if property_list  %}
				{% for property in property_list %}
				<div class="col-md-6">
					<div class="card h-50">
					  <img class="card-img-top img-fluid" src="{{ property.image.url }}" alt="">
					  <div class="card-body">
						<h4 class="card-title">{{ property.title }}</h4>
						<p class="card-text">{{ property.description }}</p>
					  </div>
					  <div class="card-footer">
						<a href="{% url 'bricks:property' property.id %}" class="btn btn-primary">Find Out More!</a>
					  </div>

				</div>
				{% endfor %}
		{% else  %}

			<p> NO PROPERTIES AVAILABLE. </p>

		{% endif %}

	</div>
</div>


{% endblock %}

bbb/bricks/templates/property.html
{% extends "base.html" %}
{% block content %}
{% load static %}


<div class="container">
    <div class="col-md-8">
        <h1> {{property.title}} </h1>

        <img src="{{ property.image.url }}" alt="">


        <p> {{property.description}}</p>


        <p> {{property.features}}</p>
    </div>
    <a href="/properties" class="btn btn-caution"> Properties </a>

</div>



{% endblock %}

bbb/bricks/templates/prospectus.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<header class="bg-primary py-5 mb-5" style="background: url("http://picsum.photos/1600/400"); background-size: cover;">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-lg-12">
          <img src="{% static "testheart.png" %}" alt="My image">

        <h1 class="display-4 text-white mt-5 mb-2">Prospectus</h1>
        <p class="lead mb-5 text-white-50">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non possimus ab labore provident mollitia. Id assumenda voluptate earum corporis facere quibusdam quisquam iste ipsa cumque unde nisi, totam quas ipsam.</p>
      </div>
    </div>
  </div>
</header>


<section class="my-5">
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto">
        <p>There is an amazing description of a prospectus here.</p>
        <p>Lorem Ipsum only takes up so much of a prospectus when you acknoledge its impact.</p>
        <p>Prospecta are very important in universal fondue formaking thorax thwarting rhumes of phasmic information.</p>
        <p class="mb-0">
          Created by <a href="www.github.com/eizode">a Prospective person</a>
        </p>
      </div>
    </div>
  </div>
</section>
{% endblock %}

bbb/bricks/templates/registerthree.1.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title> Register </title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Please Confirm your Email Address!</h1>
              </div>
              <!--<form class="user">-->
              <!--  <div class="form-group row">-->
              <!--    <div class="col-sm-6 mb-3 mb-sm-0">-->
              <!--      <input type="text" class="form-control form-control-user" id="exampleFirstName" placeholder="First Name">-->
              <!--    </div>-->
              <!--    <div class="col-sm-6">-->
              <!--      <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Last Name">-->
              <!--    </div>-->
              <!--  </div>-->
              <!--  <div class="form-group">-->
              <!--    <input type="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="Email Address">-->
              <!--  </div>-->
              <!--  <div class="form-group row">-->
              <!--    <div class="col-sm-6 mb-3 mb-sm-0">-->
              <!--      <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">-->
              <!--    </div>-->
              <!--    <div class="col-sm-6">-->
              <!--      <input type="password" class="form-control form-control-user" id="exampleRepeatPassword" placeholder="Repeat Password">-->
              <!--    </div>-->
              <!--  </div>-->
              <!--  <a href="login.html" class="btn btn-primary btn-user btn-block">-->
              <!--    Register Account-->
              <!--  </a>-->
              <!--  <hr>-->
              <!--  <a href="index.html" class="btn btn-google btn-user btn-block">-->
              <!--    <i class="fab fa-google fa-fw"></i> Register with Google-->
              <!--  </a>-->
              <!--  <a href="index.html" class="btn btn-facebook btn-user btn-block">-->
              <!--    <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook-->
              <!--  </a>-->
              <!--</form>-->
              <hr>
              <!--<div class="text-center">-->
              <!--  <a class="small" href="forgot-password.html">Forgot Password?</a>-->
              <!--</div>-->
              <!--<div class="text-center">-->
              <!--  <a class="small" href="login.html">Already have an account? Login!</a>-->
              <!--</div>-->
              <a href="/dashboard" class="form-control btn-primary">Next</a>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>


</body>
{% endblock %}

bbb/bricks/templates/registration.html
{% extends "base.html"%}

<h2 class="center"> Registration </h1>



<!-- {% if error_message %} <p> <strong> {{error_message}} </strong> </p>{% endif %}

{% if success  %} <p> <strong> { success } </strong> </p>  {% endif %} -->

{% block content %}
<h1> Register </h1>
{% endblock %}

<form action="{% url 'bricks:registration' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
    <input type="text" name="first_name" value="text">
    <label for="first_name"> First name </label>
    </div>

    <div class="form-group">
    <input type="text" name="first_name" value="text">
    <label for="first_name"> First name </label>
    </div>


    <div class="form-group">
    <input type="text" name="last_name" value="text">
    <label for="last_name"> Last name </label>

    </div>


    <div class="form-group">
    <input type="text" name="email" value="text">
    <label for="email"> Email </label>
    </div>


    <div class="form-group">
    <input type="text" name="phone_number" value="text">
    <label for="phone_number"> Phone number </label>
    </div>


    <div class="form-group">
    <input type="text" name="postcode" value="text">
	<label for="postcode"> Postcode</label>
    </div>

    <input type="submit" value="submit">
</form>